# Generated by Django 3.2.8 on 2022-02-26 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
                ('standard', models.CharField(max_length=20)),
                ('div', models.CharField(max_length=5)),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.school')),
            ],
        ),
    ]
